export const equipo = [
    {
        img: "Eze-Director",
        alt: "Ezequiel Director",
        name: "Ezequiel",
        role: "Director",
    },
    {
        img: "Mariano-Coordinacion-de-Cuentas",
        alt: "Mariano Coordinacion de Cuentas",
        name: "Mariano",
        role: "Coordinación de Cuentas",
    },
    {
        img: "Mariana-Administracion",
        alt: "Mariana Administración",
        name: "Mariana",
        role: "Administración",
    },
    {
        img: "Mateo-Coordinacion-Realizacion",
        alt: "Mateo Coordinacion de Realizacion",
        name: "Mateo",
        role: "Coordinación de Realización",
    },
    {
        img: "Cami-Video",
        alt: "Cami Video",
        name: "Cami",
        role: "Producción de Video",
    },
    {
        img: "Mati-Produccion",
        alt: "Mati Producción",
        name: "Mati",
        role: "Producción",
    },
    {
        img: "Leo-Coordinacion-Diseno",
        alt: "Leo Coordinación Diseño",
        name: "Leo",
        role: "Coordinación Diseño",
    },
    {
        img: "Floppy-Disenadora",
        alt: "Floppy Diseñadora",
        name: "Floppy",
        role: "Diseñadora",
    },
    {
        img: "Ivan-Disenador",
        alt: "Ivan Diseñador",
        name: "Ivan",
        role: "Diseñador",
    },
    {
        img: "Jorgelina-Moderacion-y-Contenidos",
        alt: "Jorgelina Moderación y Contenidos",
        name: "Jorgelina",
        role: "Moderación de redes y contenidos",
    },
    {
        img: "Mariela-Moderacion-y-Contenidos",
        alt: "Mariela Moderación y Contenidos",
        name: "Mariela",
        role: "Moderación de redes y contenidos",
    },
    {
        img: "Nahuel-Creatividad",
        alt: "Nahuel Creativo",
        name: "Nahuel",
        role: "Creativo",
    },
    {
        img: "Tomi-Creatividad",
        alt: "Tomas Creativo",
        name: "Tomás",
        role: "Creativo",
    },
    {
        img: "Joaquin-Perfomance-SEM",
        alt: "Joaquin Performance SEM",
        name: "Joaquin",
        role: "Performance SEM",
    },
    {
        img: "Karen-Performance-META",
        alt: "Karen Performance META",
        name: "Karen",
        role: "Performance META",
    },
];
